#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 30-12-09 12:20 下午
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace RecourceConverter
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SourceConfig.xsd", TypeName="AppConfigs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", IsNullable=false, ElementName="AppConfigs")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class AppConfigs
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<ApplicationSetting> appSetting;
        
        public AppConfigs()
        {
        }
        
        public AppConfigs(System.Collections.Generic.List<ApplicationSetting> appSetting)
        {
            this.appSetting = appSetting;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AppSetting")]
        public System.Collections.Generic.List<ApplicationSetting> AppSetting
        {
            get
            {
                return this.appSetting;
            }
            set
            {
                if ((this.appSetting != value))
                {
                    this.appSetting = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", TypeName="ApplicationSetting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", IsNullable=true, ElementName="ApplicationSetting")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class ApplicationSetting
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<Setting> setting;
        
        /// <remarks/>
        private string applicationName;
        
        /// <remarks/>
        private string resourcePath;
        
        /// <remarks/>
        private string resourceName;
        
        /// <remarks/>
        private bool isDefault;
        
        /// <remarks/>
        private bool isDefaultSpecified;
        
        public ApplicationSetting()
        {
        }
        
        public ApplicationSetting(System.Collections.Generic.List<Setting> setting, string applicationName, string resourcePath, string resourceName, bool isDefault, bool isDefaultSpecified)
        {
            this.setting = setting;
            this.applicationName = applicationName;
            this.resourcePath = resourcePath;
            this.resourceName = resourceName;
            this.isDefault = isDefault;
            this.isDefaultSpecified = isDefaultSpecified;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Setting")]
        public System.Collections.Generic.List<Setting> Setting
        {
            get
            {
                return this.setting;
            }
            set
            {
                if ((this.setting != value))
                {
                    this.setting = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ApplicationName")]
        public string ApplicationName
        {
            get
            {
                return this.applicationName;
            }
            set
            {
                if ((this.applicationName != value))
                {
                    this.applicationName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ResourcePath")]
        public string ResourcePath
        {
            get
            {
                return this.resourcePath;
            }
            set
            {
                if ((this.resourcePath != value))
                {
                    this.resourcePath = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ResourceName")]
        public string ResourceName
        {
            get
            {
                return this.resourceName;
            }
            set
            {
                if ((this.resourceName != value))
                {
                    this.resourceName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="IsDefault")]
        public bool IsDefault
        {
            get
            {
                return this.isDefault;
            }
            set
            {
                if ((this.isDefault != value))
                {
                    this.isDefault = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDefaultSpecified
        {
            get
            {
                return this.isDefaultSpecified;
            }
            set
            {
                if ((this.isDefaultSpecified != value))
                {
                    this.isDefaultSpecified = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", TypeName="Setting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", IsNullable=true, ElementName="Setting")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class Setting
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<LanguageSetting> languagetSetting;
        
        /// <remarks/>
        private string type;
        
        /// <remarks/>
        private string sourceFilePath;
        
        /// <remarks/>
        private string idColumn;
        
        /// <remarks/>
        private string deletedColumn;
        
        /// <remarks/>
        private string typeColumn;
        
        /// <remarks/>
        private string sheetName;
        
        /// <remarks/>
        private int rowStartIndex;
        
        /// <remarks/>
        private string totalColumns;
        
        public Setting()
        {
        }
        
        public Setting(System.Collections.Generic.List<LanguageSetting> languagetSetting, string type, string sourceFilePath, string idColumn, string deletedColumn, string typeColumn, string sheetName, int rowStartIndex, string totalColumns)
        {
            this.languagetSetting = languagetSetting;
            this.type = type;
            this.sourceFilePath = sourceFilePath;
            this.idColumn = idColumn;
            this.deletedColumn = deletedColumn;
            this.typeColumn = typeColumn;
            this.sheetName = sheetName;
            this.rowStartIndex = rowStartIndex;
            this.totalColumns = totalColumns;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LanguagetSetting")]
        public System.Collections.Generic.List<LanguageSetting> LanguagetSetting
        {
            get
            {
                return this.languagetSetting;
            }
            set
            {
                if ((this.languagetSetting != value))
                {
                    this.languagetSetting = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Type")]
        public string Type
        {
            get
            {
                return this.type;
            }
            set
            {
                if ((this.type != value))
                {
                    this.type = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="SourceFilePath")]
        public string SourceFilePath
        {
            get
            {
                return this.sourceFilePath;
            }
            set
            {
                if ((this.sourceFilePath != value))
                {
                    this.sourceFilePath = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="IdColumn")]
        public string IdColumn
        {
            get
            {
                return this.idColumn;
            }
            set
            {
                if ((this.idColumn != value))
                {
                    this.idColumn = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="DeletedColumn")]
        public string DeletedColumn
        {
            get
            {
                return this.deletedColumn;
            }
            set
            {
                if ((this.deletedColumn != value))
                {
                    this.deletedColumn = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TypeColumn")]
        public string TypeColumn
        {
            get
            {
                return this.typeColumn;
            }
            set
            {
                if ((this.typeColumn != value))
                {
                    this.typeColumn = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="SheetName")]
        public string SheetName
        {
            get
            {
                return this.sheetName;
            }
            set
            {
                if ((this.sheetName != value))
                {
                    this.sheetName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="RowStartIndex")]
        public int RowStartIndex
        {
            get
            {
                return this.rowStartIndex;
            }
            set
            {
                if ((this.rowStartIndex != value))
                {
                    this.rowStartIndex = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TotalColumns")]
        public string TotalColumns
        {
            get
            {
                return this.totalColumns;
            }
            set
            {
                if ((this.totalColumns != value))
                {
                    this.totalColumns = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", TypeName="LanguageSetting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SourceConfig.xsd", IsNullable=true, ElementName="LanguageSetting")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class LanguageSetting
    {
        
        /// <remarks/>
        private string language;
        
        /// <remarks/>
        private string languageCode;
        
        /// <remarks/>
        private string column;
        
        public LanguageSetting()
        {
        }
        
        public LanguageSetting(string language, string languageCode, string column)
        {
            this.language = language;
            this.languageCode = languageCode;
            this.column = column;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Language")]
        public string Language
        {
            get
            {
                return this.language;
            }
            set
            {
                if ((this.language != value))
                {
                    this.language = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="LanguageCode")]
        public string LanguageCode
        {
            get
            {
                return this.languageCode;
            }
            set
            {
                if ((this.languageCode != value))
                {
                    this.languageCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Column")]
        public string Column
        {
            get
            {
                return this.column;
            }
            set
            {
                if ((this.column != value))
                {
                    this.column = value;
                }
            }
        }
    }
}
