#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 29-01-10 05:58 下午
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace RecourceConverter
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Tempalte.xsd", TypeName="Templates")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Tempalte.xsd", IsNullable=false, ElementName="Templates")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class Templates : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<Template> template;
        
        /// <remarks/>
        private string @default;
        
        public Templates()
        {
        }
        
        public Templates(System.Collections.Generic.List<Template> template, string @default)
        {
            this.template = template;
            this.@default = @default;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Template")]
        public System.Collections.Generic.List<Template> Template
        {
            get
            {
                return this.template;
            }
            set
            {
                if ((this.template != value))
                {
                    this.template = value;
                    this.RaisePropertyChanged("Template");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="default")]
        public string Default
        {
            get
            {
                return this.@default;
            }
            set
            {
                if ((this.@default != value))
                {
                    this.@default = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Tempalte.xsd", TypeName="Template")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Tempalte.xsd", IsNullable=true, ElementName="Template")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class Template : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        /// <remarks/>
        private string header;
        
        /// <remarks/>
        private string body;
        
        /// <remarks/>
        private string tail;
        
        /// <remarks/>
        private string sourceFile;
        
        /// <remarks/>
        private string startRow;
        
        /// <remarks/>
        private string sheetName;
        
        /// <remarks/>
        private string keyColumn;
        
        /// <remarks/>
        private int totalColumns;
        
        /// <remarks/>
        private string deletedColumn;
        
        /// <remarks/>
        private string name;
        
        public Template()
        {
        }
        
        public Template(string header, string body, string tail, string sourceFile, string startRow, string sheetName, string keyColumn, int totalColumns, string deletedColumn, string name)
        {
            this.header = header;
            this.body = body;
            this.tail = tail;
            this.sourceFile = sourceFile;
            this.startRow = startRow;
            this.sheetName = sheetName;
            this.keyColumn = keyColumn;
            this.totalColumns = totalColumns;
            this.deletedColumn = deletedColumn;
            this.name = name;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="header")]
        public string Header
        {
            get
            {
                return this.header;
            }
            set
            {
                if ((this.header != value))
                {
                    this.header = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="body")]
        public string Body
        {
            get
            {
                return this.body;
            }
            set
            {
                if ((this.body != value))
                {
                    this.body = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="tail")]
        public string Tail
        {
            get
            {
                return this.tail;
            }
            set
            {
                if ((this.tail != value))
                {
                    this.tail = value;
                    this.RaisePropertyChanged("Tail");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="sourceFile")]
        public string SourceFile
        {
            get
            {
                return this.sourceFile;
            }
            set
            {
                if ((this.sourceFile != value))
                {
                    this.sourceFile = value;
                    this.RaisePropertyChanged("SourceFile");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="startRow")]
        public string StartRow
        {
            get
            {
                return this.startRow;
            }
            set
            {
                if ((this.startRow != value))
                {
                    this.startRow = value;
                    this.RaisePropertyChanged("StartRow");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SheetName")]
        public string SheetName
        {
            get
            {
                return this.sheetName;
            }
            set
            {
                if ((this.sheetName != value))
                {
                    this.sheetName = value;
                    this.RaisePropertyChanged("SheetName");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="keyColumn")]
        public string KeyColumn
        {
            get
            {
                return this.keyColumn;
            }
            set
            {
                if ((this.keyColumn != value))
                {
                    this.keyColumn = value;
                    this.RaisePropertyChanged("KeyColumn");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="totalColumns")]
        public int TotalColumns
        {
            get
            {
                return this.totalColumns;
            }
            set
            {
                if ((this.totalColumns != value))
                {
                    this.totalColumns = value;
                    this.RaisePropertyChanged("TotalColumns");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="deletedColumn")]
        public string DeletedColumn
        {
            get
            {
                return this.deletedColumn;
            }
            set
            {
                if ((this.deletedColumn != value))
                {
                    this.deletedColumn = value;
                    this.RaisePropertyChanged("DeletedColumn");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
