/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tools.sqltool;

import java.awt.Dimension;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import tools.sqltool.ui.form.AppConfigForm;
import tools.sqltool.ui.form.AuditFunctionForm;
import tools.sqltool.ui.form.ExportSqlForm;
import tools.sqltool.ui.form.LovManagementForm;
import tools.sqltool.ui.form.MapperForm;

/**
 *
 * @author yyi
 */
public class MainForm extends javax.swing.JFrame {
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuLov = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        mnuExportSql = new javax.swing.JMenuItem();
        mntAuditTable = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuOptions = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sql Power Tools");
        setLocationByPlatform(true);
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        desktopPane.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        desktopPane.setPreferredSize(new java.awt.Dimension(1024, 768));

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        mnuLov.setText("Lov Management");
        mnuLov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLovActionPerformed(evt);
            }
        });
        fileMenu.add(mnuLov);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Migration");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        mnuExportSql.setText("Export Sql");
        mnuExportSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExportSqlActionPerformed(evt);
            }
        });
        fileMenu.add(mnuExportSql);

        mntAuditTable.setText("Audit Table");
        mntAuditTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAuditTableActionPerformed(evt);
            }
        });
        fileMenu.add(mntAuditTable);
        fileMenu.add(jSeparator1);

        mnuOptions.setText("Options");
        mnuOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOptionsActionPerformed(evt);
            }
        });
        fileMenu.add(mnuOptions);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        if(evt.getPropertyName().equals("size")) {
            this.desktopPane.setSize((Dimension)(evt.getNewValue()));
        }
    }//GEN-LAST:event_formPropertyChange

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        //System.exit(0);
       this.dispatchEvent(new java.awt.event.WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        MapperForm form = new MapperForm();
        form.setTitle("Mapper");
        form.setVisible(true);
        desktopPane.add(form);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showOptionDialog(this, "Are you sure exit to this application?", "Prompt", 
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        if(result == JOptionPane.YES_OPTION) {
           System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mnuOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOptionsActionPerformed
       openOptionsForm();
    }//GEN-LAST:event_mnuOptionsActionPerformed

    private void mnuLovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLovActionPerformed
        LovManagementForm form = new LovManagementForm();
        form.setTitle("LOV Management");
        form.setVisible(true);
        desktopPane.add(form);
    }//GEN-LAST:event_mnuLovActionPerformed

    private void mnuExportSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExportSqlActionPerformed
        ExportSqlForm form = new ExportSqlForm();
        form.setVisible(true);
        desktopPane.add(form);
    }//GEN-LAST:event_mnuExportSqlActionPerformed

    private void mntAuditTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAuditTableActionPerformed
        AuditFunctionForm form = new AuditFunctionForm();
        form.setVisible(true);
        desktopPane.add(form);
    }//GEN-LAST:event_mntAuditTableActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mntAuditTable;
    private javax.swing.JMenuItem mnuExportSql;
    private javax.swing.JMenuItem mnuLov;
    private javax.swing.JMenuItem mnuOptions;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

    private void openOptionsForm() {
        AppConfigForm form = new AppConfigForm(this, true);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }
}
