package org.yy.studymybatis.model;

public class Author {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.id
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.name
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.email
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.id
     *
     * @return the value of author.id
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.id
     *
     * @param id the value for author.id
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.name
     *
     * @return the value of author.name
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.name
     *
     * @param name the value for author.name
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.email
     *
     * @return the value of author.email
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.email
     *
     * @param email the value for author.email
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}