package org.yy.studymybatis.model;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.value
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.value
     *
     * @return the value of tag.value
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.value
     *
     * @param value the value for tag.value
     *
     * @mbggenerated Thu Mar 10 10:14:47 CST 2011
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}